FOLDER = 'results/learn-30/'

READ_ARGS = True
LEARN_GENERATIONS = 1
INHERIT_SAMPLES = 5

POP_SIZE = 5
OFFSPRING_SIZE = 5
FUNCTION_EVALUATIONS = 15000
SIMULATION_LENGTH = 500 # 10 seconds
PARALLEL_PROCESSES = 1

PARENT_POOL = 4
MUTATION_STD = 0.01

GRID_LENGTH = 5
INITIAL_SIZE = 10
MIN_SIZE = 5
MAX_SIZE = 20
MAX_ADD_MUTATION = 3
MAX_DELETE_MUTATION = 3
MAX_CHANGE_MUTATION = 3

LEARN_LENGTH_SCALE = 0.1
LEARN_NU = 5/2
LEARN_ALPHA = 1e-10
LEARN_INHERITED_ALPHA = 2
LEARN_KAPPA = 3