FOLDER = 'results/test/'

READ_ARGS = True
LEARN_ITERATIONS = 10
INHERIT_SAMPLES = 2 # from -1 to LEARN_ITERATIONS
ENVIRONMENT = 'simple'
INHERIT_TYPE = 'best' # parent, random, none, similar or best
SOCIAL_POOL = 8

LEARN_INHERITED_ALPHA = 2
LEARN_KAPPA = 3
LEARN_LENGTH_SCALE = 0.2
LEARN_NU = 5/2
LEARN_ALPHA = 1e-10

POP_SIZE = 100
OFFSPRING_SIZE = 100
FUNCTION_EVALUATIONS = 100000
SIMULATION_LENGTH = 500 # 10 seconds
PARALLEL_PROCESSES = 100

# generational, elitist or tournament
SURVIVOR_SELECTION = 'generational'
PARENT_SELECTION = 'tournament'
CONTROLLER_TYPE = 'sine' # sine or nn

PARENT_POOL = 4
MUTATION_STD = 0.1

GRID_LENGTH = 5
MIN_INITIAL_SIZE = 10
MAX_INITIAL_SIZE = 20
MIN_SIZE = 5
MAX_SIZE = 25
MAX_ADD_MUTATION = 3
MAX_DELETE_MUTATION = 3
MAX_CHANGE_MUTATION = 3