FOLDER = 'results/test/'

READ_ARGS = True
LEARN_ITERATIONS = 10
INHERIT_SAMPLES = 2 # from -1 to LEARN_ITERATIONS
ENVIRONMENT = 'simple'
INHERIT_TYPE = 'best' # parent, random, none, similar, cell, best
SOCIAL_POOL = 8
LEARN_METHOD = 'bo'

DARWINIAN = True
RANDOM_LEARNING = False
WRITE_RANDOM_ENV = False
LEARN_INHERITED_ALPHA = 2
LEARN_KAPPA = 3
LEARN_LENGTH_SCALE = 0.2
LEARN_NU = 5/2
LEARN_ALPHA = 1e-10
BO_RESTARTS = 1

RL_EVALUATIONS_FREQUENCY = 5

POP_SIZE = 100
OFFSPRING_SIZE = 100
FUNCTION_EVALUATIONS = 100000
SIMULATION_LENGTH = 500 # 10 seconds
PARALLEL_PROCESSES = 100

# generational, elitist, tournament
SURVIVOR_SELECTION = 'generational'
PARENT_SELECTION = 'tournament'
CONTROLLER_TYPE = 'sine' # sine, nn

MAP_ELITES = True
DESCRIPTORS = ['relative_activity', 'elongation'] # relative_activity, elongation, compactness
# now we support exactly two descriptors
MAP_GRID_SIZE = 30

PARENT_POOL = 4
MUTATION_STD = 0.1

GRID_LENGTH = 5
MIN_INITIAL_SIZE = 10
MAX_INITIAL_SIZE = 20
MIN_SIZE = 5
MAX_SIZE = 25
MIN_MUTATION = 0
MAX_MUTATION = 3
CHANGE_PROB = 0.2
